security:
    encoders:
        Dte\BtsBundle\Entity\User:
            algorithm: bcrypt
            cost:      10

    role_hierarchy:
        ROLE_OPERATOR:    [ROLE_USER]
        ROLE_MANAGER:     [ROLE_USER, ROLE_OPERATOR]
        ROLE_ADMIN:       [ROLE_USER, ROLE_MANAGER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MANAGER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: DteBtsBundle:User }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|fonts)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            provider:   main
            form_login:
                check_path: dte_bts_security_check
                login_path: dte_bts_login
                always_use_default_target_path: true
            logout:
                path:   dte_bts_logout
                target: dte_bts_homepage
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
