dte_bts_homepage:
    path:     /
    defaults: { _controller: DteBtsBundle:Default:index }
dte_bts_pages:
    resource: @DteBtsBundle/Controller/DefaultController.php
    type:     annotation
dte_bts_users:
    resource: @DteBtsBundle/Controller/UserController.php
    type:     annotation
dte_bts_projects:
    resource: @DteBtsBundle/Controller/ProjectController.php
    type:     annotation

