services:
    form.type.dte_btsbundle_issue:
        class: Dte\BtsBundle\Form\IssueType
        tags:
            - {name: form.type, alias: dte_btsbundle_issue}
        arguments: ["@security.context", "@doctrine"]
    dte_bts_issue.subscriber:
        class: Dte\BtsBundle\EventListener\IssueSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments: ["@service_container"]
    dte_bts_activity.manager:
        class: Dte\BtsBundle\Manager\ActivityManager
        arguments: ["@service_container"]
    dte_bts_activity.subscriber:
        class: Dte\BtsBundle\EventListener\ActivitySubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments: ["@dte_bts_activity.manager"]
    dte_bts_notification.subscriber:
        class: Dte\BtsBundle\EventListener\NotificationSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments: ["@service_container"]
    security.access.user_voter:
        class:      Dte\BtsBundle\Security\Voter\UserVoter
        public:     false
        tags:
           - { name: security.voter }